### ISSUE TITLE
Roadmap and overview

### ISSUE THREAD

**Issue by lumiscosity** [lumiscosity/eidolist#1]
Eidolist has a simple workflow: you select the main copy, the source copy for the patch you're merging, and the patch to merge. The changelog in the patch is parsed to figure out which files and database items to merge, then all of the files are processed sequentially. If the item doesn't appear in the main copy's changelog, it is merged automatically; if it does, a diff is shown, and you get to choose. Warnings are shown when trying to merge on top of a removed item, but it otherwise allows for diffing as usual.
### Required (deadline: next submission closing)
- [x] Changelog parsing and validation
- [x] Appending the changelog to the main log
- [x] Automatic merge
- [x] Picture diffing
- [x] Map automerge
- [x] CE automerge
### Stretch goals
- [ ] Sound diffing
- [ ] Battle animation diffing (any code for this might trickle down to Toucan)
- [ ] Map diffing (will require [Toucan](https://github.com/lumiscosity/Editor) code)
- [ ] CE merge conflict resolution (requires a ground-up rewrite of Toucan's event command handling code)
